trigger:
- main


resources:
  repositories:
    - repository: newtemplates
      type: github
      name: shamimgit2021/azure_terraform_modules
      ref: refs/heads/main
      endpoint: "github_devops"

variables:
  azureServiceConnection: 'Azure_Azuredevops_serviceconnection'

steps:

# 1️⃣ Checkout Terraform GitHub repository
- checkout: azure_terraform_modules

- script: |
    echo "Current Sources Directory:"
    ls -R $(Build.SourcesDirectory)
  displayName: Debug Folder Structure

- script: terraform init
  workingDirectory: '$(Build.SourcesDirectory)/newtemplates'
  displayName: Terraform Init

- script: terraform plan
  workingDirectory: '$(Build.SourcesDirectory)/newtemplates'
  displayName: Terraform Plan

- script: terraform apply -auto-approve
  workingDirectory: '$(Build.SourcesDirectory)/newtemplates'
  displayName: Terraform Apply
